Loaded 1 valid graphs.
Bug file id: 74e888e6
Performing initial feedback checks...
Initial feedback check passed for graph 1.
/home/iany/.local/lib/python3.10/site-packages/coverage/inorout.py:519: CoverageWarning: Module networkx was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")
105, 0.4853329658508301
2, 1.765084981918335
1, 2.01958966255188
2, 3.533773899078369
2, 8.135659217834473
Ctrl+C pressed, finalizing...
Finalizing process...
count 237635
There were 152 graphs saved in the corpus.
Time spent: 119.996 minutes.
Exception: {0: "Error: 'int' object has no attribute 'is_directed'", <networkx.classes.graph.Graph object at 0x7f804f58de10>: 'NetworkX Error: Disconnected graph: Ambiguous solution for bipartite sets.', <networkx.classes.graph.Graph object at 0x7f804f58e260>: "NetworkX Error: ('Connectivity is undefined ', 'for the null graph.')", <networkx.classes.graph.Graph object at 0x7f804c1c33a0>: 'NetworkX Error: Graph is not bipartite.'}
Exception graphs saved to /home/iany/GraphFuzz/Log/max_matching_corpus_exceptions.pkl
Total Bugs Found:
Checking completed.
